### PR TITLE
Laravel 7.x Shift

### PR DESCRIPTION
**Pull request by cazzerson**
This pull request includes the changes for upgrading to Laravel 7.x. Feel free to commit any additional changes to the `shift-68859` branch.

**Before merging**, you need to:

- Checkout the `shift-68859` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by cazzerson** [comment]
:warning: Laravel 7 adds CORS middleware and defaults the `middlewarePriority` internally so you only need to overwrite this property for customizations.

Shift attempted to automate these changes, but you should compare your `app/Http/Kernel.php`  with the [default Laravel 7 version](https://github.com/laravel-shift/laravel-7.x/blob/master/app/Http/Kernel.php) to finalize any changes.

**Comment by cazzerson** [comment]
:information_source: Laravel 7 upgraded to Symfony 5 which passes instances of the `Throwable` interface instead of `Exception` instances to core components like the `Exceptions\Handler`.

Shift [automated this change](https://github.com/UNC-Libraries/wilson-clue-app/pull/47/commits/adc884c59afd0a145b6a6421b6230a2db076bfb2?w=1). However, if you receive a `Throwable` type mismatch error there may be additional references you need to convert.

**Comment by cazzerson** [comment]
:information_source: Laravel 7 moved the Authentication components into a separate [`laravel/ui` package](https://github.com/laravel/ui), which includes the _make_ commands as well as the traits related to authentication.

Shift added this dependency for convenience. However, if you do not plan to use the Authentication components, you may remove this dependency as well as the `Auth` controllers from your application.

**Comment by cazzerson** [comment]
:information_source: Shift detected the use of Markdown mail templates. In Laravel 7, Markdown mail templates expect unindented HTML, because indentation has special meaning within Markdown.

Shift [automated this change](https://github.com/UNC-Libraries/wilson-clue-app/pull/47/commits/eabd4788f03fe9dc5f01ca3a060be9d39bd55223?w=1) for Laravel's default mail templates. However, you may consider re-publishing these instead to take advantage of recent design updates. You may do so by running the command:

```sh
php artisan vendor:publish --tag=laravel-mail --force
```

**Comment by cazzerson** [comment]
:warning: The `MAIL_DRIVER` environment variable was renamed in Laravel 7 to `MAIL_MAILER` in order to support multiple mail configurations.

Shift attempted to [automate this change](https://github.com/UNC-Libraries/wilson-clue-app/pull/47/commits/a833c97cc9d8472479c094e8bf3fc3223187efb3?w=1), but you should review any additional environment configuration and update to the new variable name.

**Comment by cazzerson** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/UNC-Libraries/wilson-clue-app/pull/47/commits/4cc9c2b3e226cf1f0215aeb9b8f30523bcf6dfe0?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert 4cc9c2b3` and make the [config file changes](https://github.com/laravel-shift/laravel-6.0/pull/7/commits/e3379a9dcc2b08adf5934a99148366838371bc68) manually.

**Comment by cazzerson** [comment]
:warning: Laravel 7 uses a new date format when serializing models. The previous format was `2019-12-02 20:01:00`. Now, dates are serialized using an ISO-8601 compatible date format of `2019-12-02T20:01:00.283041Z` in `UTC`.

**This does not affect how dates are stored**. Only how they are serialized when using the `toArray` or `toJson` Eloquent methods.

If you need to preserve the previous format, you may override the `serializeDate` method on your model. Review the [Date Serialization](https://laravel.com/docs/7.x/upgrade#date-serialization) section of the _Upgrade Guide_ for more details.

**Comment by cazzerson** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 5. If you are directly interacting with any Symfony component, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/5.x/UPGRADE-5.0.md) for additional changes.

**Comment by cazzerson** [comment]
:warning: Laravel 7.x has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes or security updates. Shift recommends continuing to upgrade to the latest version (Laravel 9.x).

For tips on running multiple Shifts effectively, watch [upgrading old Laravel applications](https://laravelshift.com/videos/upgrading-old-laravel-applications).

**Review by lfarrell — APPROVED** [review]
Looks good from what I can tell.

**Pull request merged**
